### ISSUE TITLE
The training code

### ISSUE THREAD

**Issue by txw1997** [yiren-jian/LabelHalluc#1]
Hello, thank you for the excellent work. But I want to train my own dataset. Can you provide the training code?

**Comment by yiren-jian** [comment]
Hello Xuwen,

Thanks for your interest. This work is mainly evaluated on 4 well-studied few-shot benchmarks, i.e. miniImageNet, tieredImageNet, FC100 and CIFAR-FS. Usually you (1) pre-train a feature embedding model and then (2) fine-tune on the novel support set. The novelty of our this work lies on the second phase. For the first phase of pre-training, we have tried RFS, SKD and IER in the paper. But any pre-training strategies should work. We use the code of `train_supervised.py` from [RFS](https://github.com/WangYueFt/rfs), `train_selfsupervison.py` from [SKD](https://github.com/brjathu/SKD) and `train.py` from [IER](https://github.com/nayeemrizve/invariance-equivariance) and we found their code works well, producing results close to what they reported (But in general, IER > SKD > RFS). I encourage you to follow their code (maybe a slight modification is required for SKD to bypass some error). Their code is easy to read as well.

Best,
Yiren

**Comment by txw1997** [comment]
Yes, the key point is the phase two: finetune on the novel set. So I must code this part according the paper? I just find the evaluation in this repo. 

Thank you

**Comment by txw1997** [comment]
I got it, thanks.

**Comment by yiren-jian** [comment]
OK, I see. The fine-tuning, training with novel support set with pseudo-labeled base set is coded in  `LabelHalluc/eval/meta_eval_SoftPseudoLabel.py `.
