### ISSUE TITLE
The Technical Appendix of your paper

### ISSUE THREAD

**Issue by wanghao14** [yiren-jian/LabelHalluc#2]
Hi, yiren. Thanks very much for sharing your code! And I am really interested in the content of Technical Appendix which you mentioned in your paper, would you like to share it?

**Comment by yiren-jian** [comment]
Hi WangHao,

Thanks for your interest. I have uploaded the appendix to my [website](https://cs.dartmouth.edu/~yirenjian/).

Best,
Yiren
