### ISSUE TITLE
Request pretrained weight for tieredImageNet

### ISSUE THREAD

**Issue by ByeonggeunKim** [yiren-jian/LabelHalluc#4]
Hi Yiren,

Thank you for all the code and pretrained weights you provided. They are really helpful to reproduce your works.
I found out that pretrained weights for tieredImageNet is not in the dropbox.
Could you please provide the pretrained weights for tieredImageNet too?

Best.

**Comment by yiren-jian** [comment]
Here you are: https://github.com/yiren-jian/Embedding-Learning-FSL

Note that these models are re-trained after the publication (as requested). For SKD, there're models trained with different suggested hyper-parameters.
