### ISSUE TITLE
Request pretrained weight for tieredImageNet

### ISSUE THREAD

**Issue by oijt894** [yiren-jian/LabelHalluc#5]
Hi Yiren,

Thank you for all the code and the pre-trained weights you provided which are really helpful in reproducing your work.
I found the pre-trained weights for tieredImageNet in this dropbox "https://www.dropbox.com/sh/gxmu8d75a9grfph/AABOPOoTZmu2wnKnLYL1AKv9a?dl=0" from https://github.com/yiren-jian/Embedding-Learning-FSL. 

BTW, it seems that both the two pre-trained weights of IER for 5-shot. Could you provide those for the 1-shot case, as well?

Thanks!

**Comment by yiren-jian** [comment]
For baseline IER, the pretrained backbone (embedding) should be the same for 5-shot and 1-shot (or any n-shot).

Yiren
